In [2]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [13]:
df.head(10)

        entity code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138
3  Afghanistan  AFG  1953            29.4521
4  Afghanistan  AFG  1954            29.6975
5  Afghanistan  AFG  1955            30.3660
6  Afghanistan  AFG  1956            30.8303
7  Afghanistan  AFG  1957            31.3451
8  Afghanistan  AFG  1958            31.8400
9  Afghanistan  AFG  1959            32.3365

In [66]:
df.shape

(20217, 3)

In [9]:
df.columns.tolist()

['entity', 'code', 'year', 'life_expectancy_0']

In [10]:
df.dtypes

entity                   str
code                     str
year                   int64
life_expectancy_0    float64
dtype: object

In [15]:
df.describe()

               year  life_expectancy_0
count  21565.000000       21565.000000
mean    1976.992812          61.942232
std       38.461606          12.925912
min     1543.000000          10.989100
25%     1962.000000          52.703000
50%     1982.000000          64.479900
75%     2003.000000          71.978900
max     2023.000000          86.372400

In [3]:
#REnombrar columnas
df.rename(columns={"entity" : "pais"},inplace=True) #Implace para mantener el cambio
df.head()

          pais code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138
3  Afghanistan  AFG  1953            29.4521
4  Afghanistan  AFG  1954            29.6975

In [4]:
# case ayuda a diferenciar mayusculas con minusculas ( estricto )
# na ayuda a controlar nulos
# regex permite buscar con simbolos:
#   ^ = Que empiece con
#   $ = que termine con
df[(df["year"] == 1970) & (df["pais"].str.contains("^K",case=False,regex=True)) ][["pais","year","life_expectancy_0"]]

            pais  year  life_expectancy_0
9591  Kazakhstan  1970            60.0490
9668       Kenya  1970            54.1427
9742    Kiribati  1970            54.3802
9816      Kosovo  1970            54.0023
9891      Kuwait  1970            67.9771
9965  Kyrgyzstan  1970            58.1840

In [5]:
df.set_index("pais")

            code  year  life_expectancy_0
pais
Afghanistan  AFG  1950            28.1563
Afghanistan  AFG  1951            28.5836
Afghanistan  AFG  1952            29.0138
Afghanistan  AFG  1953            29.4521
Afghanistan  AFG  1954            29.6975
...          ...   ...                ...
Zimbabwe     ZWE  2019            61.0603
Zimbabwe     ZWE  2020            61.5300
Zimbabwe     ZWE  2021            60.1347
Zimbabwe     ZWE  2022            62.3601
Zimbabwe     ZWE  2023            62.7748

[21565 rows x 3 columns]

In [6]:
df.head()

          pais code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138
3  Afghanistan  AFG  1953            29.4521
4  Afghanistan  AFG  1954            29.6975

In [55]:
df.loc[df["code"].notnull(),["year","life_expectancy_0"]].head()

             year  life_expectancy_0
pais
Afghanistan  1950            28.1563
Afghanistan  1951            28.5836
Afghanistan  1952            29.0138
Afghanistan  1953            29.4521
Afghanistan  1954            29.6975

In [ ]:
#Borra valores nulos
df.dropna(subset=["code"],inplace=True)
df.isnull().sum()

Antes: (20217, 3)
Depue: (20217, 3)

In [ ]:
#agrupar
resultado = (
    df.groupby("pais")["life_expectancy_0"].mean().sort_values(ascending=True)
)

resultado.head(10)

pais
USSR                        32.700000
South Sudan                 37.841631
Sierra Leone                43.189605
Mali                        43.760793
Niger                       44.187513
East Timor                  44.684692
Nigeria                     44.855897
Chad                        45.007786
Central African Republic    45.084431
Malawi                      45.554985
Name: life_expectancy_0, dtype: float64

In [88]:
new_df = df[df["year"].between(1970,2023)]
resultado = (
    new_df.groupby("pais")["life_expectancy_0"].mean().sort_values(ascending=True)
)
print(resultado)

pais
South Sudan                 41.076146
Central African Republic    47.109006
Sierra Leone                47.234867
Chad                        47.391891
Niger                       47.716867
                              ...
Switzerland                 79.105678
San Marino                  79.849424
Japan                       79.861796
Andorra                     80.412854
Monaco                      80.541217
Name: life_expectancy_0, Length: 246, dtype: float64

In [9]:
df[(df["pais"].str.contains("^Mex",case=False,regex=True)) & (df["year"] == 1910)][["pais","year","life_expectancy_0"]]

         pais  year  life_expectancy_0
12389  Mexico  1910               28.0